from config.llm_judge import (
    ORACLE_DISCRIMINATOR_VARIANT,
)

HUMAN_REVIEW_RESULTS_DIR = "human_review/results"
HUMAN_REVIEW_N_SAMPLES = 50
HUMAN_REVIEW_N_EVAL_SAMPLES_PER_FOLDER_URI = 13
HUMAN_REVIEW_RANDOM_SEED = 42
HUMAN_REVIEW_DATA_VARIANT = ORACLE_DISCRIMINATOR_VARIANT
HUMAN_REVIEW_ORACLE_DISCRIMINATOR_TIMESTAMP = None
HUMAN_REVIEW_NO_REQUEST_CATEGORY_PLACEHOLDER = "conversation_closer|notification|..."
HUMAN_REVIEW_ORACLE_ANSWERABILITY_CATEGORY_PLACEHOLDER = "other_master_program|private_case_state|..."
